/*
Response.js
===========
An HTTP response from a ResourceService; generated by evaluating an application resource

Responsibilities:
 - Maintains headers and a body
 - Provides a rendering function which defines how the agent should handle the response
*/

goog.provide('link.Response');

link.Response = function() {
    // :TODO:
}

